# Use Node.js as the base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy rest of frontend code
COPY . .

# Expose port 3000 for the frontend
EXPOSE 3000

# Start the frontend app
CMD ["npm", "start"]